version: '3'

services:
  dev-linux:
    build: .
    container_name: dev.linux.containers
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/home/devuser/workspace
    restart: unless-stopped